### ISSUE TITLE
Broken link describing the LOFAR cycles and observations

### ISSUE THREAD

**Issue by elboyran** [EOSC-LOFAR/LTA#13]
The [Lofar Long Term Archive](https://lta.lofar.eu/Lofar) page refers to a list of all LOFAR observing cycles and approved projects. That [link](http://www.astron.nl/radio-observatory/cycles-allocations-and-observing-schedules/cycles-allocations-and-observing-schedu) is broken. 

To be forwarded to ASTRON partners?

**Comment by HannoSpreeuw** [comment]
Done

**Comment by HannoSpreeuw** [comment]
[This](http://www.astron.nl/radio-observatory/observing/cycles-allocations-and-observing-schedules/cycles-allocations-and-observ) is the correct link.

**Comment by elboyran** [comment]
Yes, but the [main page](https://lta.lofar.eu/) still refers to the broken link.
Shouldn't we tell ASTRON to fix it?

**Comment by HannoSpreeuw** [comment]
By "Done" I meant to say that ASTRON has been notified.
(Replying to "To be forwarded to ASTRON partners?")
