### ISSUE TITLE
Inconsistent FAIR metrics names (F1A and F1B) at the FAIR Metrics repository 

### ISSUE THREAD

**Issue by elboyran** [EOSC-LOFAR/LTA#14]
Why F1A and F1B are used as metrics identifiers in the [FAIR metrics repo](https://github.com/FAIRMetrics/Metrics)?

- All other metrics with more refined sub-metrics have the numeric name conversion, i.e. A1.1 and A1.2

- In the [FAIR Data Principles explained ](https://www.dtls.nl/fair-data/fair-principles-explained/)F1 is not split in two. 

The splitting is not a bad idea (persistence from uniqueness), but (at least the naming) should be consistent with the rest and resources such as the [FAIR Data Principles explained](https://www.dtls.nl/fair-data/fair-principles-explained/).

Related to issue #2 .

**Comment by arnikz** [comment]
Good question and I agree with you w.r.t. consistency. However, the FAIR metrics is work in progress whereas the principles were published more than 2 years ago.
