### ISSUE TITLE
Document the reasons for selecting this subset of tables

### ISSUE THREAD

**Issue by arnikz** [EOSC-LOFAR/LTA#15]
I haven't found this info on the wiki.

https://github.com/EOSC-LOFAR/LTA/tree/master/tables

**Comment by lbogaardt** [comment]
Documenten [here](https://github.com/EOSC-LOFAR/LTA/wiki): The terms "Epoch, Spectral Window, Pointing, FWHM, Duration" were identified by Astronomy expert Hanno Spreeuw as relevant. In Ontology, columns of the MS were identified as relevant. This lead to the selection of "Observation", "Pointing" and "SubArrayPointing" as the 3 DB tables to analyse.
