### ISSUE TITLE
Semantify the LOFAR DBView using domain-specific vocabs/ontologies

### ISSUE THREAD

**Issue by elboyran** [EOSC-LOFAR/LTA#3]
- [x] Find domain-specific vocabs/ontologies
 - [x] Map vocabs/ontologies to [LOFAR DBView](https://lta-dbview.lofar.eu/DbView) tables

**Comment by elboyran** [comment]
[Ontology of Astronomical Object Types](http://www.ivoa.net/documents/Notes/AstrObjectOntology/)
[Astronomy/Science ontology](https://www.astro.umd.edu/%7Eeshaya/astro-onto/)

**Comment by arnikz** [comment]
Both links present in the [wiki](https://github.com/EOSC-LOFAR/LTA/wiki). The preliminary mappings were defined using OpenRefine (see the files [here](https://github.com/EOSC-LOFAR/LTA/tree/master/openrefine)).
