### ISSUE TITLE
Configure and deploy FAIR Data Point on HPC Cloud

### ISSUE THREAD

**Issue by elboyran** [EOSC-LOFAR/LTA#5]
- [x] Clone/fork [FAIR Data Point](https://www.research-software.nl/software/fairdatapoint)
 - [x] Edit `configure.ini`
 - [x] Deploy to HPC

**Comment by felipeZ** [comment]
Temporal URL: http://lofar-lta-55956.lofarpipelines-astron.surf-hosted.nl:8080/doc/index.html

**Comment by arnikz** [comment]
Done.
