### ISSUE TITLE
Configure and deploy Virtuoso together with Apache Solr on HPC Cloud

### ISSUE THREAD

**Issue by elboyran** [EOSC-LOFAR/LTA#6]
- [ ] Use Docker Compose to deploy [Virtuoso](https://hub.docker.com/r/candygene/docker-virtuoso/) (use dev branch) and [Apache Solr](https://hub.docker.com/r/_/solr/)
- [ ] Configure Solr to index RDF in the Virtuoso Quad Store
- [ ] Search for a GUI for faceted search

**Comment by felipeZ** [comment]
![rdf](https://user-images.githubusercontent.com/4108663/41846876-6fae1f38-7878-11e8-9a08-368c169b2a01.jpg)

**Comment by arnikz** [comment]
We decided to deploy & orchestrate FDP and Virtuoso (excluding Solr for time being).
